# 02 — Data Collection
Goal: pull all available match and player data from the API, flatten it, and save as parquet files under `data/processed/`.

In [1]:
import sys
sys.path.insert(0, '..')

import datetime
import pandas as pd
from pathlib import Path
from src.api.client import PadelAPIClient
from src.processing.flatten import flatten_match, flatten_player, flatten_tournament

client = PadelAPIClient(requests_per_minute=10)
PROCESSED_DIR = Path('../data/processed')
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

today = datetime.date.today().isoformat()
print(f'Collecting data up to {today}')

Collecting data up to 2026-03-25

## 1. Players
Fetch all players across all pages.

In [2]:
raw_players = client.get_all_players()
print(f'Fetched {len(raw_players)} players')

df_players = pd.DataFrame([flatten_player(p) for p in raw_players])
df_players['birthdate'] = pd.to_datetime(df_players['birthdate'], errors='coerce')
print(df_players.shape)
df_players.head()

  page 1: +15 items (total so far: 15/909)
  page 2: +15 items (total so far: 30/909)
  page 3: +15 items (total so far: 45/909)
  page 4: +15 items (total so far: 60/909)
  page 5: +15 items (total so far: 75/909)
  429 rate limited — waiting 30s before retry (3 left)...
  page 6: +15 items (total so far: 90/909)
  page 7: +15 items (total so far: 105/909)
  page 8: +15 items (total so far: 120/909)
  page 9: +15 items (total so far: 135/909)
  page 10: +15 items (total so far: 150/909)
  429 rate limited — waiting 30s before retry (3 left)...
  page 11: +15 items (total so far: 165/909)
  page 12: +15 items (total so far: 180/909)
  page 13: +15 items (total so far: 195/909)
  page 14: +15 items (total so far: 210/909)
  page 15: +15 items (total so far: 225/909)
  429 rate limited — waiting 30s before retry (3 left)...
  page 16: +15 items (total so far: 240/909)
  page 17: +15 items (total so far: 255/909)
  page 18: +15 items (total so far: 270/909)
  page 19: +15 items (total so far: 285/909)
  page 20: +15 items (total so far: 300/909)
  429 rate limited — waiting 30s before retry (3 left)...
  page 21: +15 items (total so far: 315/909)
  page 22: +15 items (total so far: 330/909)
  page 23: +15 items (total so far: 345/909)
  page 24: +15 items (total so far: 360/909)
  page 25: +15 items (total so far: 375/909)
  429 rate limited — waiting 30s before retry (3 left)...
  page 26: +15 items (total so far: 390/909)
  page 27: +15 items (total so far: 405/909)
  page 28: +15 items (total so far: 420/909)
  page 29: +15 items (total so far: 435/909)
  page 30: +15 items (total so far: 450/909)
  429 rate limited — waiting 30s before retry (3 left)...
  page 31: +15 items (total so far: 465/909)
  page 32: +15 items (total so far: 480/909)
  page 33: +15 items (total so far: 495/909)
  page 34: +15 items (total so far: 510/909)
  page 35: +15 items (total so far: 525/909)
  429 rate limited — waiting 30s before retry (3 left)...
  page 36: +15 items (total so far: 540/909)
  page 37: +15 items (total so far: 555/909)
  page 38: +15 items (total so far: 570/909)
  page 39: +15 items (total so far: 585/909)
  page 40: +15 items (total so far: 600/909)
  429 rate limited — waiting 30s before retry (3 left)...
  page 41: +15 items (total so far: 615/909)
  page 42: +15 items (total so far: 630/909)
  page 43: +15 items (total so far: 645/909)
  page 44: +15 items (total so far: 660/909)
  page 45: +15 items (total so far: 675/909)
  429 rate limited — waiting 30s before retry (3 left)...
  page 46: +15 items (total so far: 690/909)
  page 47: +15 items (total so far: 705/909)
  page 48: +15 items (total so far: 720/909)
  page 49: +15 items (total so far: 735/909)
  page 50: +15 items (total so far: 750/909)
  429 rate limited — waiting 30s before retry (3 left)...
  page 51: +15 items (total so far: 765/909)
  page 52: +15 items (total so far: 780/909)
  page 53: +15 items (total so far: 795/909)
  page 54: +15 items (total so far: 810/909)
  page 55: +15 items (total so far: 825/909)
  429 rate limited — waiting 30s before retry (3 left)...
  page 56: +15 items (total so far: 840/909)
  page 57: +15 items (total so far: 855/909)
  page 58: +15 items (total so far: 870/909)
  page 59: +15 items (total so far: 885/909)
  page 60: +15 items (total so far: 900/909)
  429 rate limited — waiting 30s before retry (3 left)...
  page 61: +9 items (total so far: 909/909)
Fetched 909 players
(909, 12)

,player_id,name,short_name,category,ranking,points,nationality,birthdate,age,height,hand,side
0,371,Aaron Segura,Segura,men,799.0,22.0,US,2004-12-03,21.0,NaN,None,None
1,339,Abdulaziz Redha,Redha,men,895.0,18.0,KW,1998-02-25,28.0,NaN,None,None
2,344,Abdulaziz Saadon Alkuwari,Saadon,men,2734.0,NaN,QA,1979-11-13,46.0,179.0,None,drive
3,186,Abdulla Alhijji,Alhijji,men,525.0,49.0,QA,1990-01-25,36.0,177.0,None,backhand
4,336,Abdullah Alabdullah,Alabdullah,men,813.0,22.0,SA,2002-09-04,23.0,NaN,None,None

## 2. Matches
Fetch all completed matches (paginated). The free tier covers the last 6 months.

In [5]:
raw_matches = client.get_all_matches(before_date=today)
print(f'Fetched {len(raw_matches)} matches total')

finished = [m for m in raw_matches if m.get('status') == 'finished']
print(f'Finished matches: {len(finished)}')

df_matches = pd.DataFrame([flatten_match(m) for m in finished])
df_matches['played_at'] = pd.to_datetime(df_matches['played_at'], errors='coerce')
print(df_matches.shape)
df_matches.head()

  page 1: +15 items (total so far: 15/6997)
  page 2: +15 items (total so far: 30/6997)
  page 3: +15 items (total so far: 45/6997)
  page 4: +15 items (total so far: 60/6997)
  page 5: +15 items (total so far: 75/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 6: +15 items (total so far: 90/6997)
  page 7: +15 items (total so far: 105/6997)
  page 8: +15 items (total so far: 120/6997)
  page 9: +15 items (total so far: 135/6997)
  page 10: +15 items (total so far: 150/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 11: +15 items (total so far: 165/6997)
  page 12: +15 items (total so far: 180/6997)
  page 13: +15 items (total so far: 195/6997)
  page 14: +15 items (total so far: 210/6997)
  page 15: +15 items (total so far: 225/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 16: +15 items (total so far: 240/6997)
  page 17: +15 items (total so far: 255/6997)
  page 18: +15 items (total so far: 270/6997)
  page 19: +15 items (total so far: 285/6997)
  page 20: +15 items (total so far: 300/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 21: +15 items (total so far: 315/6997)
  page 22: +15 items (total so far: 330/6997)
  page 23: +15 items (total so far: 345/6997)
  page 24: +15 items (total so far: 360/6997)
  page 25: +15 items (total so far: 375/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 26: +15 items (total so far: 390/6997)
  page 27: +15 items (total so far: 405/6997)
  page 28: +15 items (total so far: 420/6997)
  page 29: +15 items (total so far: 435/6997)
  page 30: +15 items (total so far: 450/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 31: +15 items (total so far: 465/6997)
  page 32: +15 items (total so far: 480/6997)
  page 33: +15 items (total so far: 495/6997)
  page 34: +15 items (total so far: 510/6997)
  page 35: +15 items (total so far: 525/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 36: +15 items (total so far: 540/6997)
  page 37: +15 items (total so far: 555/6997)
  page 38: +15 items (total so far: 570/6997)
  page 39: +15 items (total so far: 585/6997)
  page 40: +15 items (total so far: 600/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 41: +15 items (total so far: 615/6997)
  page 42: +15 items (total so far: 630/6997)
  page 43: +15 items (total so far: 645/6997)
  page 44: +15 items (total so far: 660/6997)
  page 45: +15 items (total so far: 675/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 46: +15 items (total so far: 690/6997)
  page 47: +15 items (total so far: 705/6997)
  page 48: +15 items (total so far: 720/6997)
  page 49: +15 items (total so far: 735/6997)
  page 50: +15 items (total so far: 750/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 51: +15 items (total so far: 765/6997)
  page 52: +15 items (total so far: 780/6997)
  page 53: +15 items (total so far: 795/6997)
  page 54: +15 items (total so far: 810/6997)
  page 55: +15 items (total so far: 825/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 56: +15 items (total so far: 840/6997)
  page 57: +15 items (total so far: 855/6997)
  page 58: +15 items (total so far: 870/6997)
  page 59: +15 items (total so far: 885/6997)
  page 60: +15 items (total so far: 900/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 61: +15 items (total so far: 915/6997)
  page 62: +15 items (total so far: 930/6997)
  page 63: +15 items (total so far: 945/6997)
  page 64: +15 items (total so far: 960/6997)
  page 65: +15 items (total so far: 975/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 66: +15 items (total so far: 990/6997)
  page 67: +15 items (total so far: 1005/6997)
  page 68: +15 items (total so far: 1020/6997)
  page 69: +15 items (total so far: 1035/6997)
  page 70: +15 items (total so far: 1050/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 71: +15 items (total so far: 1065/6997)
  page 72: +15 items (total so far: 1080/6997)
  page 73: +15 items (total so far: 1095/6997)
  page 74: +15 items (total so far: 1110/6997)
  page 75: +15 items (total so far: 1125/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 76: +15 items (total so far: 1140/6997)
  page 77: +15 items (total so far: 1155/6997)
  page 78: +15 items (total so far: 1170/6997)
  page 79: +15 items (total so far: 1185/6997)
  page 80: +15 items (total so far: 1200/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 81: +15 items (total so far: 1215/6997)
  page 82: +15 items (total so far: 1230/6997)
  page 83: +15 items (total so far: 1245/6997)
  page 84: +15 items (total so far: 1260/6997)
  page 85: +15 items (total so far: 1275/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 86: +15 items (total so far: 1290/6997)
  page 87: +15 items (total so far: 1305/6997)
  page 88: +15 items (total so far: 1320/6997)
  page 89: +15 items (total so far: 1335/6997)
  page 90: +15 items (total so far: 1350/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 91: +15 items (total so far: 1365/6997)
  page 92: +15 items (total so far: 1380/6997)
  page 93: +15 items (total so far: 1395/6997)
  page 94: +15 items (total so far: 1410/6997)
  page 95: +15 items (total so far: 1425/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 96: +15 items (total so far: 1440/6997)
  page 97: +15 items (total so far: 1455/6997)
  page 98: +15 items (total so far: 1470/6997)
  page 99: +15 items (total so far: 1485/6997)
  page 100: +15 items (total so far: 1500/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 101: +15 items (total so far: 1515/6997)
  page 102: +15 items (total so far: 1530/6997)
  page 103: +15 items (total so far: 1545/6997)
  page 104: +15 items (total so far: 1560/6997)
  page 105: +15 items (total so far: 1575/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 106: +15 items (total so far: 1590/6997)
  page 107: +15 items (total so far: 1605/6997)
  page 108: +15 items (total so far: 1620/6997)
  page 109: +15 items (total so far: 1635/6997)
  page 110: +15 items (total so far: 1650/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 111: +15 items (total so far: 1665/6997)
  page 112: +15 items (total so far: 1680/6997)
  page 113: +15 items (total so far: 1695/6997)
  page 114: +15 items (total so far: 1710/6997)
  page 115: +15 items (total so far: 1725/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 116: +15 items (total so far: 1740/6997)
  page 117: +15 items (total so far: 1755/6997)
  page 118: +15 items (total so far: 1770/6997)
  page 119: +15 items (total so far: 1785/6997)
  page 120: +15 items (total so far: 1800/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 121: +15 items (total so far: 1815/6997)
  page 122: +15 items (total so far: 1830/6997)
  page 123: +15 items (total so far: 1845/6997)
  page 124: +15 items (total so far: 1860/6997)
  page 125: +15 items (total so far: 1875/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 126: +15 items (total so far: 1890/6997)
  page 127: +15 items (total so far: 1905/6997)
  page 128: +15 items (total so far: 1920/6997)
  page 129: +15 items (total so far: 1935/6997)
  page 130: +15 items (total so far: 1950/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 131: +15 items (total so far: 1965/6997)
  page 132: +15 items (total so far: 1980/6997)
  page 133: +15 items (total so far: 1995/6997)
  page 134: +15 items (total so far: 2010/6997)
  page 135: +15 items (total so far: 2025/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 136: +15 items (total so far: 2040/6997)
  page 137: +15 items (total so far: 2055/6997)
  page 138: +15 items (total so far: 2070/6997)
  page 139: +15 items (total so far: 2085/6997)
  page 140: +15 items (total so far: 2100/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 141: +15 items (total so far: 2115/6997)
  page 142: +15 items (total so far: 2130/6997)
  page 143: +15 items (total so far: 2145/6997)
  page 144: +15 items (total so far: 2160/6997)
  page 145: +15 items (total so far: 2175/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 146: +15 items (total so far: 2190/6997)
  page 147: +15 items (total so far: 2205/6997)
  page 148: +15 items (total so far: 2220/6997)
  page 149: +15 items (total so far: 2235/6997)
  page 150: +15 items (total so far: 2250/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 151: +15 items (total so far: 2265/6997)
  page 152: +15 items (total so far: 2280/6997)
  page 153: +15 items (total so far: 2295/6997)
  page 154: +15 items (total so far: 2310/6997)
  page 155: +15 items (total so far: 2325/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 156: +15 items (total so far: 2340/6997)
  page 157: +15 items (total so far: 2355/6997)
  page 158: +15 items (total so far: 2370/6997)
  page 159: +15 items (total so far: 2385/6997)
  page 160: +15 items (total so far: 2400/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 161: +15 items (total so far: 2415/6997)
  page 162: +15 items (total so far: 2430/6997)
  page 163: +15 items (total so far: 2445/6997)
  page 164: +15 items (total so far: 2460/6997)
  page 165: +15 items (total so far: 2475/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 166: +15 items (total so far: 2490/6997)
  page 167: +15 items (total so far: 2505/6997)
  page 168: +15 items (total so far: 2520/6997)
  page 169: +15 items (total so far: 2535/6997)
  page 170: +15 items (total so far: 2550/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 171: +15 items (total so far: 2565/6997)
  page 172: +15 items (total so far: 2580/6997)
  page 173: +15 items (total so far: 2595/6997)
  page 174: +15 items (total so far: 2610/6997)
  page 175: +15 items (total so far: 2625/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 176: +15 items (total so far: 2640/6997)
  page 177: +15 items (total so far: 2655/6997)
  page 178: +15 items (total so far: 2670/6997)
  page 179: +15 items (total so far: 2685/6997)
  page 180: +15 items (total so far: 2700/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 181: +15 items (total so far: 2715/6997)
  page 182: +15 items (total so far: 2730/6997)
  page 183: +15 items (total so far: 2745/6997)
  page 184: +15 items (total so far: 2760/6997)
  page 185: +15 items (total so far: 2775/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 186: +15 items (total so far: 2790/6997)
  page 187: +15 items (total so far: 2805/6997)
  page 188: +15 items (total so far: 2820/6997)
  page 189: +15 items (total so far: 2835/6997)
  page 190: +15 items (total so far: 2850/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 191: +15 items (total so far: 2865/6997)
  page 192: +15 items (total so far: 2880/6997)
  page 193: +15 items (total so far: 2895/6997)
  page 194: +15 items (total so far: 2910/6997)
  page 195: +15 items (total so far: 2925/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 196: +15 items (total so far: 2940/6997)
  page 197: +15 items (total so far: 2955/6997)
  page 198: +15 items (total so far: 2970/6997)
  page 199: +15 items (total so far: 2985/6997)
  page 200: +15 items (total so far: 3000/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 201: +15 items (total so far: 3015/6997)
  page 202: +15 items (total so far: 3030/6997)
  page 203: +15 items (total so far: 3045/6997)
  page 204: +15 items (total so far: 3060/6997)
  page 205: +15 items (total so far: 3075/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 206: +15 items (total so far: 3090/6997)
  page 207: +15 items (total so far: 3105/6997)
  page 208: +15 items (total so far: 3120/6997)
  page 209: +15 items (total so far: 3135/6997)
  page 210: +15 items (total so far: 3150/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  429 rate limited — waiting 0s before retry (2 left)...
  page 211: +15 items (total so far: 3165/6997)
  page 212: +15 items (total so far: 3180/6997)
  page 213: +15 items (total so far: 3195/6997)
  page 214: +15 items (total so far: 3210/6997)
  page 215: +15 items (total so far: 3225/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 216: +15 items (total so far: 3240/6997)
  page 217: +15 items (total so far: 3255/6997)
  page 218: +15 items (total so far: 3270/6997)
  page 219: +15 items (total so far: 3285/6997)
  page 220: +15 items (total so far: 3300/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 221: +15 items (total so far: 3315/6997)
  page 222: +15 items (total so far: 3330/6997)
  page 223: +15 items (total so far: 3345/6997)
  page 224: +15 items (total so far: 3360/6997)
  page 225: +15 items (total so far: 3375/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 226: +15 items (total so far: 3390/6997)
  page 227: +15 items (total so far: 3405/6997)
  page 228: +15 items (total so far: 3420/6997)
  page 229: +15 items (total so far: 3435/6997)
  page 230: +15 items (total so far: 3450/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 231: +15 items (total so far: 3465/6997)
  page 232: +15 items (total so far: 3480/6997)
  page 233: +15 items (total so far: 3495/6997)
  page 234: +15 items (total so far: 3510/6997)
  page 235: +15 items (total so far: 3525/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 236: +15 items (total so far: 3540/6997)
  page 237: +15 items (total so far: 3555/6997)
  page 238: +15 items (total so far: 3570/6997)
  page 239: +15 items (total so far: 3585/6997)
  page 240: +15 items (total so far: 3600/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 241: +15 items (total so far: 3615/6997)
  page 242: +15 items (total so far: 3630/6997)
  page 243: +15 items (total so far: 3645/6997)
  page 244: +15 items (total so far: 3660/6997)
  page 245: +15 items (total so far: 3675/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 246: +15 items (total so far: 3690/6997)
  page 247: +15 items (total so far: 3705/6997)
  page 248: +15 items (total so far: 3720/6997)
  page 249: +15 items (total so far: 3735/6997)
  page 250: +15 items (total so far: 3750/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 251: +15 items (total so far: 3765/6997)
  page 252: +15 items (total so far: 3780/6997)
  page 253: +15 items (total so far: 3795/6997)
  page 254: +15 items (total so far: 3810/6997)
  page 255: +15 items (total so far: 3825/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 256: +15 items (total so far: 3840/6997)
  page 257: +15 items (total so far: 3855/6997)
  page 258: +15 items (total so far: 3870/6997)
  page 259: +15 items (total so far: 3885/6997)
  page 260: +15 items (total so far: 3900/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 261: +15 items (total so far: 3915/6997)
  page 262: +15 items (total so far: 3930/6997)
  page 263: +15 items (total so far: 3945/6997)
  page 264: +15 items (total so far: 3960/6997)
  page 265: +15 items (total so far: 3975/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 266: +15 items (total so far: 3990/6997)
  page 267: +15 items (total so far: 4005/6997)
  page 268: +15 items (total so far: 4020/6997)
  page 269: +15 items (total so far: 4035/6997)
  page 270: +15 items (total so far: 4050/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 271: +15 items (total so far: 4065/6997)
  page 272: +15 items (total so far: 4080/6997)
  page 273: +15 items (total so far: 4095/6997)
  page 274: +15 items (total so far: 4110/6997)
  page 275: +15 items (total so far: 4125/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 276: +15 items (total so far: 4140/6997)
  page 277: +15 items (total so far: 4155/6997)
  page 278: +15 items (total so far: 4170/6997)
  page 279: +15 items (total so far: 4185/6997)
  page 280: +15 items (total so far: 4200/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 281: +15 items (total so far: 4215/6997)
  page 282: +15 items (total so far: 4230/6997)
  page 283: +15 items (total so far: 4245/6997)
  page 284: +15 items (total so far: 4260/6997)
  page 285: +15 items (total so far: 4275/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 286: +15 items (total so far: 4290/6997)
  page 287: +15 items (total so far: 4305/6997)
  page 288: +15 items (total so far: 4320/6997)
  page 289: +15 items (total so far: 4335/6997)
  page 290: +15 items (total so far: 4350/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 291: +15 items (total so far: 4365/6997)
  page 292: +15 items (total so far: 4380/6997)
  page 293: +15 items (total so far: 4395/6997)
  page 294: +15 items (total so far: 4410/6997)
  page 295: +15 items (total so far: 4425/6997)
  429 rate limited — waiting 31s before retry (3 left)...
  page 296: +15 items (total so far: 4440/6997)
  page 297: +15 items (total so far: 4455/6997)
  page 298: +15 items (total so far: 4470/6997)
  page 299: +15 items (total so far: 4485/6997)
  page 300: +15 items (total so far: 4500/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 301: +15 items (total so far: 4515/6997)
  page 302: +15 items (total so far: 4530/6997)
  page 303: +15 items (total so far: 4545/6997)
  page 304: +15 items (total so far: 4560/6997)
  page 305: +15 items (total so far: 4575/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 306: +15 items (total so far: 4590/6997)
  page 307: +15 items (total so far: 4605/6997)
  page 308: +15 items (total so far: 4620/6997)
  page 309: +15 items (total so far: 4635/6997)
  page 310: +15 items (total so far: 4650/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 311: +15 items (total so far: 4665/6997)
  page 312: +15 items (total so far: 4680/6997)
  page 313: +15 items (total so far: 4695/6997)
  page 314: +15 items (total so far: 4710/6997)
  page 315: +15 items (total so far: 4725/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 316: +15 items (total so far: 4740/6997)
  page 317: +15 items (total so far: 4755/6997)
  page 318: +15 items (total so far: 4770/6997)
  page 319: +15 items (total so far: 4785/6997)
  page 320: +15 items (total so far: 4800/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 321: +15 items (total so far: 4815/6997)
  page 322: +15 items (total so far: 4830/6997)
  page 323: +15 items (total so far: 4845/6997)
  page 324: +15 items (total so far: 4860/6997)
  page 325: +15 items (total so far: 4875/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 326: +15 items (total so far: 4890/6997)
  page 327: +15 items (total so far: 4905/6997)
  page 328: +15 items (total so far: 4920/6997)
  page 329: +15 items (total so far: 4935/6997)
  page 330: +15 items (total so far: 4950/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 331: +15 items (total so far: 4965/6997)
  page 332: +15 items (total so far: 4980/6997)
  page 333: +15 items (total so far: 4995/6997)
  page 334: +15 items (total so far: 5010/6997)
  page 335: +15 items (total so far: 5025/6997)
  429 rate limited — waiting 30s before retry (3 left)...
  page 336: +15 items (total so far: 5040/6997)
  page 337: +15 items (total so far: 5055/6997)
  page 338: +15 items (total so far: 5070/6997)

AttributeError: 'str' object has no attribute 'get'

In [7]:
import importlib
import src.processing.flatten as flatten_mod
importlib.reload(flatten_mod)
from src.processing.flatten import flatten_match, flatten_player, flatten_tournament

In [8]:
finished = [m for m in raw_matches if m.get('status') == 'finished']
print(f'Finished matches: {len(finished)}')

df_matches = pd.DataFrame([flatten_match(m) for m in finished])
df_matches['played_at'] = pd.to_datetime(df_matches['played_at'], errors='coerce')
print(df_matches.shape)
df_matches.head()

Finished matches: 5170
(5170, 16)

,match_id,tournament_id,category,round,round_name,played_at,status,winner,duration,t1_p1,t1_p2,t2_p1,t2_p2,sets_won_t1,sets_won_t2,n_sets
0,7417,728,men,32,Round of 64,2026-03-24,finished,team_1,01:12,148.0,64.0,107.0,159.0,2,0,2
1,7422,728,men,32,Round of 64,2026-03-24,finished,team_1,02:07,452.0,98.0,163.0,465.0,2,0,2
2,7429,728,men,32,Round of 64,2026-03-24,finished,team_2,01:17,197.0,250.0,151.0,199.0,0,2,2
3,7430,728,men,32,Round of 64,2026-03-24,finished,team_2,01:58,284.0,228.0,92.0,211.0,1,2,3
4,7433,728,men,32,Round of 64,2026-03-24,finished,team_2,01:04,1248.0,1249.0,157.0,210.0,0,2,2

## 3. Tournaments
Fetch metadata for every tournament referenced in the match data.

In [9]:
tournament_ids = df_matches['tournament_id'].dropna().astype(int).unique()
print(f'Unique tournaments in match data: {len(tournament_ids)}')

raw_tournaments = [client.get_tournament(int(tid)) for tid in tournament_ids]
df_tournaments = pd.DataFrame([flatten_tournament(t) for t in raw_tournaments])
df_tournaments['start_date'] = pd.to_datetime(df_tournaments['start_date'], errors='coerce')
df_tournaments['end_date'] = pd.to_datetime(df_tournaments['end_date'], errors='coerce')
print(df_tournaments.shape)
df_tournaments.head()

Unique tournaments in match data: 95
  429 rate limited — waiting 30s before retry (3 left)...
  429 rate limited — waiting 30s before retry (3 left)...
  429 rate limited — waiting 30s before retry (3 left)...

HTTPError: 404 Client Error: Not Found for url: https://padelapi.org/api/tournaments/511

In [11]:
raw_tournaments = []
for tid in tournament_ids:
    try:
        raw_tournaments.append(client.get_tournament(int(tid)))
    except Exception as e:
        print(f"  Skipping tournament {tid}: {e}")

df_tournaments = pd.DataFrame([flatten_tournament(t) for t in raw_tournaments])
df_tournaments['start_date'] = pd.to_datetime(df_tournaments['start_date'], errors='coerce')
df_tournaments['end_date'] = pd.to_datetime(df_tournaments['end_date'], errors='coerce')
print(df_tournaments.shape)
df_tournaments.head()

  Skipping tournament 511: 404 Client Error: Not Found for url: https://padelapi.org/api/tournaments/511
  429 rate limited — waiting 30s before retry (3 left)...
  429 rate limited — waiting 30s before retry (3 left)...
  429 rate limited — waiting 30s before retry (3 left)...
  429 rate limited — waiting 30s before retry (3 left)...
  429 rate limited — waiting 30s before retry (3 left)...
  429 rate limited — waiting 30s before retry (3 left)...
  429 rate limited — waiting 30s before retry (3 left)...
  429 rate limited — waiting 30s before retry (3 left)...
  429 rate limited — waiting 30s before retry (3 left)...
  429 rate limited — waiting 30s before retry (3 left)...
  429 rate limited — waiting 30s before retry (3 left)...
  429 rate limited — waiting 30s before retry (3 left)...
  429 rate limited — waiting 30s before retry (3 left)...
  429 rate limited — waiting 30s before retry (3 left)...
  429 rate limited — waiting 30s before retry (3 left)...
(94, 9)

,tournament_id,season_id,name,location,country,level,status,start_date,end_date
0,728,5,Miami P1 2026,Miami,US,p1,live,2026-03-23,2026-03-29
1,727,5,Cancún P2 2026,Cancún,MX,p2,finished,2026-03-16,2026-03-22
2,726,5,Gijón P2 2026,Gijón,ES,p2,finished,2026-03-02,2026-03-08
3,778,6,FIP Gold Ponta Delgada,Açores,PT,fip_gold,finished,2026-03-04,2026-03-08
4,725,5,Riyadh Season P1 2026,Riyadh,SA,p1,finished,2026-02-07,2026-02-14

## 4. Save to Parquet

In [12]:
df_players.to_parquet(PROCESSED_DIR / 'players.parquet', index=False)
df_matches.to_parquet(PROCESSED_DIR / 'matches.parquet', index=False)
df_tournaments.to_parquet(PROCESSED_DIR / 'tournaments.parquet', index=False)
print('Saved:')
print(f'  players.parquet    {len(df_players):>5} rows')
print(f'  matches.parquet    {len(df_matches):>5} rows')
print(f'  tournaments.parquet {len(df_tournaments):>4} rows')

Saved:
  players.parquet      909 rows
  matches.parquet     5170 rows
  tournaments.parquet   94 rows

## 5. Dataset Summary

In [13]:
# Date range
print('Match date range:', df_matches['played_at'].min().date(), '→', df_matches['played_at'].max().date())
print()

# Matches by category
print('Matches by category:')
print(df_matches['category'].value_counts().to_string())
print()

# Matches by round
print('Matches by round:')
print(df_matches[['round', 'round_name']].value_counts().sort_index().to_string())
print()

# Null rates for key columns
key_cols = ['winner', 'sets_won_t1', 'sets_won_t2', 't1_p1', 't1_p2', 't2_p1', 't2_p2']
null_pct = df_matches[key_cols].isna().mean().mul(100).round(1)
print('Null % for key columns:')
print(null_pct.to_string())

Match date range: 2023-02-22 → 2026-03-24

Matches by category:
category
men      3286
women    1884

Matches by round:
round  round_name
1      Finals          152
2      Semifinals      308
4      Quarter         618
8      Round of 16    1189
16     Round of 32    2124
32     Round of 64     779

Null % for key columns:
winner         0.0
sets_won_t1    0.0
sets_won_t2    0.0
t1_p1          1.1
t1_p2          1.1
t2_p1          1.4
t2_p2          1.4

In [4]:
df_players.to_parquet('../data/processed/players.parquet', index=False)
print(f'Saved {len(df_players)} players')

Saved 909 players